// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppMain: typeof import('./src/components/layout/components/AppMain.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    Experiments: typeof import('./src/views/Experiments/index.vue')['default']
    ExperimentsDetails: typeof import('./src/views/ExperimentsDetails/index.vue')['default']
    Header: typeof import('./src/components/layout/components/Header/index.vue')['default']
    Home: typeof import('./src/views/Home/index.vue')['default']
    IconEpBaseball: typeof import('~icons/ep/baseball')['default']
    IconEpFold: typeof import('~icons/ep/fold')['default']
    Layout: typeof import('./src/components/layout/index.vue')['default']
    Logo: typeof import('./src/components/layout/components/Header/Logo.vue')['default']
    MainLayout: typeof import('./src/components/layout/MainLayout.vue')['default']
    Models: typeof import('./src/views/Models/index.vue')['default']
    NotFound: typeof import('./src/views/NotFound/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/layout/components/Sidebar/index.vue')['default']
    SideBar: typeof import('./src/components/layout/SideBar/index.vue')['default']
  }
}
