# Generated by Django 2.1.5 on 2023-07-24 14:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlgExperiments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='实验记录名称')),
                ('description', models.CharField(max_length=256, verbose_name='实验记录描述')),
                ('time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '实验记录表',
                'verbose_name_plural': '实验记录表',
                'db_table': 'ml_experiments',
            },
        ),
        migrations.CreateModel(
            name='AlgExperimentsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset', models.CharField(max_length=128, verbose_name='实验数据集')),
                ('ratio', models.FloatField(max_length=32, verbose_name='实验标记数据划分标准')),
                ('name', models.CharField(max_length=128, verbose_name='实验记录名称')),
                ('runid', models.CharField(max_length=64, verbose_name='实验运行记录ID')),
                ('duration', models.CharField(max_length=64, verbose_name='实验持续时间')),
                ('status', models.CharField(max_length=32, verbose_name='实验进行状态')),
                ('description', models.CharField(max_length=256, verbose_name='实验记录描述')),
                ('tags', models.CharField(max_length=64, verbose_name='实验性质标签')),
                ('time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.AlgExperiments')),
            ],
            options={
                'verbose_name': '实验记录表',
                'verbose_name_plural': '实验记录表',
                'db_table': 'ml_experiments_list',
            },
        ),
        migrations.CreateModel(
            name='AlgMetrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='指标名称')),
                ('value', models.CharField(max_length=32, verbose_name='指标值')),
                ('exp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.AlgExperimentsList')),
            ],
            options={
                'verbose_name': '实验算法评估指标表',
                'verbose_name_plural': '实验算法评估指标表',
                'db_table': 'ml_Metrics',
            },
        ),
        migrations.CreateModel(
            name='AlgModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='算法模型名称')),
                ('file', models.CharField(max_length=256, verbose_name='算法模型保存位置')),
                ('time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('exp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.AlgExperimentsList')),
            ],
            options={
                'verbose_name': '算法模型表',
                'verbose_name_plural': '算法模型表',
                'db_table': 'ml_algorithms',
            },
        ),
        migrations.CreateModel(
            name='AlgParameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='实验参数名称')),
                ('value', models.CharField(max_length=32, verbose_name='实验参数值')),
                ('exp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.AlgExperimentsList')),
            ],
            options={
                'verbose_name': '实验参数表',
                'verbose_name_plural': '实验参数表',
                'db_table': 'ml_Parameters',
            },
        ),
    ]
